spring.application.name=jilo-com-jurubeba
server.port=8080

# =============================
# JPA / Hibernate
# =============================
spring.jpa.open-in-view=false
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}

spring.profiles.active=dev

# =============================
# DevTools
# =============================
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.poll-interval=1000
spring.devtools.restart.quiet-period=400

# =============================
# Actuator / Info
# =============================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true

info.app.name=${spring.application.name}
info.app.version=@project.version@
info.app.encoding=@project.build.sourceEncoding@
info.java.version=@java.version@

# =============================
# SpringDoc
# =============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.show-actuator=false

# =============================
# Logging
# =============================
logging.level.root=INFO
logging.level.com.grupo3.postech.jilocomjurubeba=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# =============================
# Jackson
# =============================
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

spring.mvc.problemdetails.enabled=true

# =============================
# JWT
# =============================
security.jwt.secret=${JWT_SECRET:5fV8sXyJc1R2b3QkLm9Pz4TgYh7NwK8aR0uEiVxZcLqM2sDf}
security.jwt.expiration-ms=86400000

# desativa user default do Spring
spring.security.user.name=
spring.security.user.password=

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

