DELETE FROM cardapio;
DELETE FROM restaurante;
DELETE FROM usuario;
DELETE FROM tipo_usuario;

ALTER TABLE cardapio ALTER COLUMN id RESTART WITH 1;
ALTER TABLE restaurante ALTER COLUMN id RESTART WITH 1;
ALTER TABLE usuario ALTER COLUMN id RESTART WITH 1;
ALTER TABLE tipo_usuario ALTER COLUMN id RESTART WITH 1;
